### ISSUE TITLE
Question about the filtered LLaVA dataset

### ISSUE THREAD

**Issue by Yangyi-Chen** [UCSC-VLAA/Sight-Beyond-Text#1]
Hi, thanks for your great work. I'm wondering do you have any reference (paper) to the adopted filtered 88K GPT-generated multimodal instruction-following data since the original LLaVA paper uses a 150K dataset?

**Comment by ImKeTT** [comment]
Hi Yangyi, 

Thanks for your interest in our work. The filtered 80k visual instruction data is taken from LLaVA repository directly. It's a subset of LLaVA-Instruct-150K with non-overlapping images. Please refer to their [lightning data version](https://github.com/haotian-liu/LLaVA#lightning).

**Comment by Yangyi-Chen** [comment]
thanks so much!
